### ISSUE TITLE
events not firing ?

### ISSUE THREAD

**Issue by daslicht** [lvivski/anima#31]
Hi,
I tried to use the 'end' event but it doesn't fire :+1: 
```
$(".box").animate({
               left:'20%',
                opacity: .5,
                duration: 500,
                ease: 'ease-in-out-quad',
                delay: 100
              }).on('end', function(){
                  alert('end');
              });
```
What am i missing , please?
see live example:
http://jsbin.com/pawiho/1/edit?html,console,output

**Comment by 3bola** [comment]
live example is empty?

**Comment by daslicht** [comment]
Hm strange, anyway:
http://jsbin.com/pawiho/3/edit

**Comment by daslicht** [comment]
In safari I get graphic glitches:
    http://i.imgur.com/LafEtfh.png

**Comment by lvivski** [comment]
@daslicht here's a working example http://jsbin.com/vejuvunoku/1 (works only when output is fullscreen), you have to add `jquery.anima.js` and then use it as (*note the `.anima()`*)
```js
$(".box").anima().animate({
    translate:[100, 100, 100],
    opacity: .5,
    duration: 500,
    ease: 'ease-in-out-quad',
    delay: 100
}).on('end', function(){
    alert('end');
});  
```
Only absolute values are supported in `translate`. Sorry for delay, I'm sick right now.

**Comment by daslicht** [comment]
Thank you very much !
