### ISSUE TITLE
CSS easings not working

### ISSUE THREAD

**Issue by SebastianMY** [lvivski/anima#33]
First of all, amazing work!

Now, I detected an issue. If I force CSS I lost the easings.
I set up a very simple demo: http://fiddle.jshell.net/Yerba/r0kpsr6m/show/

Source: https://jsfiddle.net/Yerba/r0kpsr6m/

**Comment by lvivski** [comment]
I can definitely see both elements using easings now, they may be out of sync a bit, but css version is not linear
