### ISSUE TITLE
Enhancement: animate background color

### ISSUE THREAD

**Issue by jmcopeland** [lvivski/anima#34]
I currently use move.js but am looking to replace it with anima for its pause/resume functionality. With move.js I can animate the background color of an item using `move(element).set('background-color', 'red')`. I use this quite a bit in my app. It would be nice if anima supported such a feature.

**Comment by lvivski** [comment]
Already in the current dev version (`master`). Doesn't work for named colors, but works for `#HEX` and `rgba()`. Additional properties are named the same way as in Browser API. So `background-color` becomes `backgroundColor`, etc.
